name: Production deploy

on:
  push:
    branches: [master]

jobs:
  build_and_deploy_production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm i -g yarn
      - name: install app dependencies
        run: yarn
        env:
          CI: true
      - name: Build Production
        run: yarn build:prod
        env:
          JWT_SECRET: ${{ secrets.PRODUCTION_JWT_SECRET }}
          MONGO_CONNECTION: ${{ secrets.PRODUCTION_MONGO_CONNECTION }}
          MONGO_DATABASE: ${{ secrets.PRODUCTION_MONGO_DATABASE }}
      - name: Deploy to Production server
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: "domains/${{ secrets.PRODUCTION_DOMAIN }}/public_nodejs"
      - name: Restart domain
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key : ${{ secrets.SERVER_SSH_KEY }}
          script: devil www restart ${{ secrets.PRODUCTION_DOMAIN }}
      - name: Unfreezing query
        run: curl http://${{ secrets.PRODUCTION_DOMAIN }}/app/status